### PR TITLE
Added more functionality to reports

### PR DESCRIPTION
**Pull request by mesta88**
We can now enter a number of days to filter the report to. Specifically in the best-selling products report option, but can be copied to the best-customers option if needed.

### CODE REVIEW

**Review by richardoh95 — APPROVED** [review]
Very nice. The ability to get a custom report for any number of days is very useful. Approved.

**Review by jfelici4 — APPROVED** [review]
It worked for me. Got a strange error when I opened it in excel but that was probably something specific only to my computer. Still could view the contents anyway.

**Review by meddy7 — APPROVED** [review]
Works as intended

**Review by Asianspinmaster — COMMENTED** [review]
Looks good!

**Pull request merged**
