### PR TITLE
Added documentation and some code clean up

### PR DESCRIPTION
**Pull request by richardoh95**
Added documentation for all my code. Cleaned up code in both delete functions in Inventory.java and Orders.java as well as their respective menu options. Also added verification for some user input in inventoryTable and ordersTable menus. Cleaned up some code in getRecommend method in Orders.java

### CODE REVIEW

**Review by jfelici4 — APPROVED** [review]
Approved. Possibility for infinite input loop given an empty inventory database, but the event is unlikely.

**Review by Asianspinmaster — COMMENTED** [review]
Approved

**Review by mesta88 — APPROVED** [review]
Useful comments added throughout. Nice job

**Review by mesta88 — APPROVED** [review]
Latest commit makes it much cleaner. Nice job

**Pull request merged**
