### PR TITLE
Read Function bug fix

### PR DESCRIPTION
**Pull request by mesta88**
Changed read function to return sale price and wholesale prices as doubles rather than ints.

### CODE REVIEW

**Review by mesta88 — COMMENTED** [review]
Ignore 2nd commit. Accidentally on wrong branch. 3rd commit is a revert to remove 2nd commit.

**Review by jfelici4 — APPROVED** [review]
Approved. Casting as a double ensures the decimals don't get truncated by the time it is converted to a string for output into the command line.

**Review by richardoh95 — APPROVED** [review]
Approved. Will keep an eye out for more inconsistencies in data typing. Approved.

**Comment by meddy7** [comment]
Approved. Works as intended.

**Pull request merged**
